using Hrm.Contracts;
using Microsoft.EntityFrameworkCore;

namespace Hrm.Modules.Employees.Infrastructure.Persistence;

public interface IEmployeesDatabaseInitializer
{
    Task InitializeAsync(CancellationToken cancellationToken);
}

public sealed class EmployeesDatabaseInitializer(EmployeesDbContext dbContext) : IEmployeesDatabaseInitializer
{
    public async Task InitializeAsync(CancellationToken cancellationToken)
    {
        var strategy = dbContext.Database.CreateExecutionStrategy();
        await strategy.ExecuteAsync(async () =>
        {
            await using var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken);
            await dbContext.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(7246012028)", cancellationToken);

            await dbContext.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS departments (
                    dept_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    dept_code varchar(50) NOT NULL UNIQUE,
                    dept_name varchar(255) NOT NULL,
                    description text NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                CREATE TABLE IF NOT EXISTS positions (
                    position_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    position_code varchar(50) NOT NULL UNIQUE,
                    title varchar(255) NOT NULL,
                    base_salary numeric(15, 2) NOT NULL DEFAULT 0,
                    allowance numeric(15, 2) NOT NULL DEFAULT 0,
                    description text NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                ALTER TABLE departments ADD COLUMN IF NOT EXISTS dept_code varchar(50);
                ALTER TABLE departments ADD COLUMN IF NOT EXISTS dept_name varchar(255);
                ALTER TABLE departments ADD COLUMN IF NOT EXISTS description text NULL;
                ALTER TABLE departments ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
                ALTER TABLE departments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

                UPDATE departments SET dept_code = 'DEPT_' || dept_id WHERE dept_code IS NULL;
                UPDATE departments SET dept_name = 'Phòng ' || dept_id WHERE dept_name IS NULL;

                ALTER TABLE positions ADD COLUMN IF NOT EXISTS position_code varchar(50);
                ALTER TABLE positions ADD COLUMN IF NOT EXISTS title varchar(255);
                ALTER TABLE positions ADD COLUMN IF NOT EXISTS base_salary numeric(15, 2) NOT NULL DEFAULT 0;
                ALTER TABLE positions ADD COLUMN IF NOT EXISTS allowance numeric(15, 2) NOT NULL DEFAULT 0;
                ALTER TABLE positions ADD COLUMN IF NOT EXISTS description text NULL;
                ALTER TABLE positions ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
                ALTER TABLE positions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

                UPDATE positions SET position_code = 'POS_' || position_id WHERE position_code IS NULL;

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'positions' AND column_name = 'position_name'
                    ) THEN
                        EXECUTE 'UPDATE positions SET title = position_name WHERE title IS NULL';
                    END IF;
                END $$;

                UPDATE positions SET title = 'Vị trí ' || position_id WHERE title IS NULL;

                ALTER TABLE employees ADD COLUMN IF NOT EXISTS emp_code varchar(50);
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS full_name varchar(255);
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS dept_id bigint NULL;
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS position_id bigint NULL;
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS email varchar(255) NULL;
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS phone varchar(50) NULL;
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS address text NULL;
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS hire_date date NULL;
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS status varchar(50) NOT NULL DEFAULT 'ACTIVE';
                ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

                UPDATE employees SET emp_code = 'EMP' || LPAD(emp_id::text, 4, '0') WHERE emp_code IS NULL;
                UPDATE employees SET full_name = 'Nhân viên ' || emp_id WHERE full_name IS NULL;
                UPDATE employees SET email = 'emp' || emp_id || '@saigonretail.vn' WHERE email IS NULL OR email = '';
                UPDATE employees SET phone = '090000000' || LPAD(emp_id::text, 2, '0') WHERE phone IS NULL OR phone = '';

                CREATE TABLE IF NOT EXISTS employee_timeline_events (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    emp_id bigint NOT NULL,
                    event_type varchar(50) NOT NULL,
                    title varchar(255) NOT NULL,
                    description text NOT NULL,
                    timestamp timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    created_by_user_id bigint NULL,
                    created_by_name varchar(255) NULL
                );

                CREATE INDEX IF NOT EXISTS ix_employee_timeline_events_emp_id
                    ON employee_timeline_events(emp_id);
                """, cancellationToken);

            // Seed Employee permissions into permissions table if missing
            var permissionsToEnsure = new[]
            {
                (PermissionCodes.EmployeeRead, "Xem danh sách và chi tiết nhân sự"),
                (PermissionCodes.EmployeeWrite, "Tạo mới và cập nhật hồ sơ nhân sự"),
                (PermissionCodes.EmployeeTransfer, "Điều chuyển phòng ban nhân sự"),
                (PermissionCodes.EmployeeOffboard, "Thực hiện offboarding nhân sự")
            };

            foreach (var (code, desc) in permissionsToEnsure)
            {
                await dbContext.Database.ExecuteSqlInterpolatedAsync($"""
                    INSERT INTO permissions (perm_id, permission_code, description)
                    SELECT COALESCE(MAX(perm_id), 0) + 1, {code}, {desc}
                    FROM permissions
                    HAVING NOT EXISTS (SELECT 1 FROM permissions WHERE permission_code = {code});
                    """, cancellationToken);

                await dbContext.Database.ExecuteSqlInterpolatedAsync($"""
                    INSERT INTO role_permissions (role_id, perm_id)
                    SELECT r.role_id, p.perm_id
                    FROM roles r
                    CROSS JOIN permissions p
                    WHERE upper(r.role_name) IN ('ADMIN', 'HR_MANAGER')
                      AND p.permission_code = {code}
                      AND NOT EXISTS (
                          SELECT 1 FROM role_permissions rp
                          WHERE rp.role_id = r.role_id AND rp.perm_id = p.perm_id);
                    """, cancellationToken);
            }

            await transaction.CommitAsync(cancellationToken);
        });
    }
}
